### ISSUE TITLE
Campo Estado Inconsistência

### ISSUE THREAD

**Issue by ThiagoS332** [ThiagoS332/CC8550-Judocas_System#37]
O campo Estado aceita mais do que dois caracteres e dígitos.

É necessário atualizar a documentação para indicar qual a maneira correta de se preenche-lo.

**Comment by LucaMilla** [comment]
Fechado adicionando limitador de caracteres no campo "estado"
![image](https://user-images.githubusercontent.com/61246777/203882231-16b9168d-8a2c-4b9e-a96b-87f018de489d.png)
